### ISSUE TITLE
Unchecked runtime.lastError while running tabs.get: No tab with id

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Fauxbar#18]
This error seems to come up a lot on the background page:

```
_generated_background_page.html:1

Unchecked runtime.lastError while running tabs.get: No tab with id: 701.
at toggleContextMenu (chrome-extension://hibkhcnpkakjniplpfblaoikiggkopka/js/background-new.js:1012:14)
at chrome-extension://hibkhcnpkakjniplpfblaoikiggkopka/js/background-new.js:674:32
```

**Comment by ChrisNZL** [comment]
Appears to be a harmless race condition - the tab no longer exists sometimes when `chrome.tabs.get` is called to see if we should create a context menu or not. Haven't noticed any abnormal behaviour.
